---
- name : Install node and NPM
  hosts: webserver
  tasks: 
  - name: update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name : Install nodeJS and NPM
    apt:
      pkg:
        - nodejs
        - npm
- name: Add the new user
  hosts: webserver
  tasks:
   - name: create linux user
     user:
      name: "{{linux_user}}"
      comment: James Admin
      shell: /bin/bash
      groups: admin
- name: Deploy Node JS App
  hosts: webserver
  become: True
  become_user: "{{linux_user}}"
  vars:
    - location: /root/ansible/simple-nodejs
    - version: 1.0.0
    - destination: "/home/{{linux_user}}"
  tasks:
   - name: copy nodejs folder to a server
     copy: 
       src: "{{location}}/nodejs-app-{{{version}}.tgz"
       dest: "{{destination}}/app-1.0.0.tgz"
   - name : Unpacking the nodejs file
     unarchive:
        src: "{{destination}}/app-1.0.0.tgz"
        dest: "{{destination}}"
   - name: Install dependencies
     npm:
      path: "{{destination}}/package"
   - name: Start the application
     command: 
       chdir: "{{destination}}/package/app"
       cmd: node server
     async: 1000
     poll: 0
   - name: Ensure App is running
     shell: ps aux | grep node
     register: app_status
   - debug: msg = {{app_status.stdout_lines}}


